---
netplan_configurations:
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - "{{ ansible_host }}/24"
      nameservers:
        addresses:
          - "{{ dns_addresses.0 }}"
          - "{{ dns_addresses.1 }}"
      gateway4: "{{ default_gateway4 }}"
      match:
        macaddress: "{{ ansible_facts['eth0']['macaddress'] }}"
      mtu: 1442
      set-name: eth0
      
haproxy_balances:
  - frontend:
      mode: tcp
      option: tcplog
    frontend_name: kube-apiserver-front
    backend:
      mode: tcp
      balance: roundrobin
    backend_name: kube-apiserver-backend
    server_group_name: k8s_masters
    balance_target_port: 6443
    balance_bind_port: 6443
