apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: default
spec:
    containers:
    - name: curl
      image: arunvelsriram/utils
      command:
         - sleep
         - "3600"
      imagePullPolicy: IfNotPresent
    restartPolicy: Always