--- # Configure

- name: Configure edge server
  hosts: edges
  remote_user: "{{ ansible_user }}"
  become: true
  become_method: sudo
  connection: ssh
  gather_facts: true
  roles:
    - basic_setup
    - haproxy
    # iptables
