---

- name: Creates manifests directory
  ansible.builtin.file:
    path: "{{ custom_manifests_dir }}"
    state: directory
    mode: 0666

- name: Download calico operator
  ansible.builtin.get_url:
    url: "{{ calico_operator_manifest_url }}"
    dest: "{{ custom_manifests_id }}/calico_operator.yml"
    mode: '0664'

- name: Apply calico operator
  kubernetes.core.k8s:
    state: present
    src: "{{ custom_manifests_id }}/calico_operator.yml"

- name: Download calico custom objects
  ansible.builtin.get_url:
    url: "{{ calico_custom_manifest_url }}"
    dest: "{{ custom_manifests_id }}/calico_custom_operators.yml"
    mode: '0664'

- name: Apply calico custom objects
  kubernetes.core.k8s:
    state: present
    src: "{{ custom_manifests_id }}/calico_custom_operators.yml"