---

- name: Init kuber cluster master node
  become: true
  ansible.builtin.command: >
    kubeadm init --pod-network-cidr=10.244.0.0/16
    --control-plane-endpoint "{{ hostvars[groups['k8s_lb'].0].ansible_host }}:{{ api_server_default_port }}"



- ansible.builtin.import_tasks: configure.yml

# - name: Enable cni plugin
#   become: true
#   ansible.builtin.command: >
#     kubectl apply -f 
#     {{ flannel_kubernetes_manifest_url }}

- name: Wait for master to get ready
  ansible.builtin.command: "/usr/bin/kubectl get nodes"
  register: nodes
  until: "'Ready' in nodes.stdout"   
  retries: 6
  delay: 5
  when: wait_for_master_to_get_ready
