---
# - name: Pull essential images
#   become: true
#   ansible.builtin.command: kubeadm config images pull

- name: Update apt cache and install kubectl
  ansible.builtin.apt:
    name: "kubectl={{ kuber_version }}"
    update_cache: true
    cache_valid_time: 3600
    allow_downgrade: yes
  retries: 3
  delay: 10
  become: true

- name: Populate service facts
  ansible.builtin.service_facts:

- ansible.builtin.import_tasks: reset.yml
  when: 
    - "ansible_facts.services['kubelet.service'].state == 'running'"
    - "tear_down_cluster"

- ansible.builtin.import_tasks: init.yml
  when: >
    is_kube_master_genesis and
    ansible_facts.services['kubelet.service'].state != 'running' 
    or (register_tear_down is defined and register_tear_down.changed)

- ansible.builtin.import_tasks: command.yml
  when: is_kube_master_genesis

- ansible.builtin.import_tasks: join.yml
  when: >
    not is_kube_master_genesis and
    ansible_facts.services['kubelet.service'].state != 'running' 
    or (register_tear_down is defined and register_tear_down.changed)
