---

- name: reset kuber cluster master node
  become: true
  ansible.builtin.command: kubeadm reset --force
  register: register_tear_down

- name: delete kube config
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /root/.kube/config
    - "/home/{{ ansible_user }}/.kube/config"
