---
netplan_configurations:
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - "{{ ansible_host }}/24"
      nameservers:
        addresses:
          - "{{ dns_addresses.0 }}"
          - "{{ dns_addresses.1 }}"
      gateway4: "{{ default_gateway4 }}"
      match:
        macaddress: "{{ ansible_facts['eth0']['macaddress'] }}"
      mtu: 1442
      set-name: eth0
