---
netplan_config_root: /etc/netplan/
netplan_config_file_name: 50-cloud-init.yaml
netplan_config_file: "{{ netplan_config_root }}{{ netplan_config_file_name }}"
netplan_default_template_name: default.netplan.j2
netplan_template_name: "{{netplan_default_template_name}}"
netplan_configurations:
#   ethernets:
#     eth0:
#       dhcp4: false
#       addresses:
#         - "{{ ansible_host }}/24"
#       nameservers:
#         addresses:
#           - "{{ default_dns_addresses.0 }}"
#           - "{{ default_dns_addresses.1 }}"
#       gateway4: "{{ default_gateway4 }}"
#       match:
#         macaddress: "{{ ansible_facts['eth0']['macaddress'] }}"
#       mtu: 1442
#       set-name: eth0
